/*
 * ADC_Private.h
 *
 *  Created on: May 10, 2024
 *      Author: 20102
 */

#include "../../../Common/StdType.h"

#ifndef MCAL_ADC_HEADER_ADC_PRIVATE_H_
#define MCAL_ADC_HEADER_ADC_PRIVATE_H_

/*ADC_MUX*/
typedef union
{
	u8 BYTE;
	struct
	{
		u8 MUX0 : 1;
		u8 MUX1 : 1;
		u8 MUX2 : 1;
		u8 MUX3 : 1;
		u8 MUX4 : 1;
		u8 ADLAR: 1;
		u8 REFS0: 1;
		u8 REFS1: 1;
	}Bits;
}Type_ADC_MUX_REG;


/*ADCSRA*/
typedef union
{
	u8 BYTE;
	struct
	{
		u8  ADPS0:1;
		u8  ADPS1:1;
		u8  ADPS2:1;
		u8  ADIE :1;
		u8  ADIF :1;
		u8  ADATE:1;
		u8  ADSC :1;
		u8  ADEN  :1;
	}Bits;
}Type_ADCSRA_REG;

typedef enum
{

	AREF_Pin_INTERNAL_VREF_OFF,
	AVCC_With_External_CAP,
	RESERVED,
	Internal_2_56V

}Type_Reference_Selection;


typedef enum
{
	ADC0_SINGLE_ENDED_INPUT,
	ADC1_SINGLE_ENDED_INPUT,
	ADC2_SINGLE_ENDED_INPUT,
	ADC3_SINGLE_ENDED_INPUT,
	ADC4_SINGLE_ENDED_INPUT,
	ADC5_SINGLE_ENDED_INPUT,
	ADC6_SINGLE_ENDED_INPUT,
	ADC7_SINGLE_ENDED_INPUT,

	ADC0_POS_ADC0_NEG_10X_DOUBLE_ENDED_INPUT,
	ADC1_POS_ADC0_NEG_10X_DOUBLE_ENDED_INPUT,

	ADC0_POS_ADC0_NEG_200X_DOUBLE_ENDED_INPUT,
	ADC1_POS_ADC0_NEG_200X_DOUBLE_ENDED_INPUT,

	ADC2_POS_ADC2_NEG_10X_DOUBLE_ENDED_INPUT,
	ADC3_POS_ADC2_NEG_10X_DOUBLE_ENDED_INPUT,

	ADC2_POS_ADC2_NEG_200X_DOUBLE_ENDED_INPUT,
	ADC3_POS_ADC2_NEG_200X_DOUBLE_ENDED_INPUT,

	ADC0_POS_ADC1_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC1_POS_ADC1_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC2_POS_ADC1_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC3_POS_ADC1_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC4_POS_ADC1_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC5_POS_ADC1_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC6_POS_ADC1_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC7_POS_ADC1_NEG_1X_DOUBLE_ENDED_INPUT,

	ADC0_POS_ADC2_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC1_POS_ADC2_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC2_POS_ADC2_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC3_POS_ADC2_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC4_POS_ADC2_NEG_1X_DOUBLE_ENDED_INPUT,
	ADC5_POS_ADC2_NEG_1X_DOUBLE_ENDED_INPUT,

	ADC_1_22V_VBG_SINGLE_ENDED_INPUT,
	ADC_GND_SINGLE_ENDED_INPUT

}Type_CHANNEL;

typedef enum
{

	DIV_2,
	DIV_2_,
	DIV_4,
	DIV_8,
	DIV_16,
	DIV_32,
	DIV_64,
	DIV_128

}ADC_Prescaler;

typedef enum
{
	FREE_RUN,
	AnalogCOMP,
	EXTERNAL_INTERRUPT_0,
	T0_CM,
	T0_OV,
	T1_CM_B,
	T1_OV,
	T1_CaptureEVENT,
	NO_AUTO_TRIGGER_CONTROLED_CONVERSION

}ADC_Auto_Trigger_Source;

typedef struct
{

	ADC_Auto_Trigger_Source TRIGGER;
	Type_Reference_Selection REFRENCE_VOLT;
	ADC_Prescaler PRE_SCALE;

}ADC_Config;


/*SPIOR*/
#define ADTS2 7
#define ADTS1 6
#define ADTS0 5


#define MUXNum 5

#define prescalemask 	 0x07
#define ADCCSRAmask  	 0xF8
#define AdcMuxMask 	     0xE0
#define ADC_TRIGGER_MASK 0x1F

#define ADC_REFRENCE_VOLT_MASK  0x3F

#define ADC_Group_ID	  1
#define ADC_PIN_DIRECTION 0

#endif /* MCAL_ADC_HEADER_ADC_PRIVATE_H_ */
